=== sourcesense/modeshape-stone/third-parties/joda-time/JodaTimeContrib/holiday/src/java/org/joda/time/contrib/holiday/src/joda-holiday.dtd
<!ELEMENT joda-holiday-information (locale-holiday-information*)>
<!ELEMENT holiday-information (id,week?,day*)>
<!ATTLIST holiday-information
  id CDATA #REQUIRED
  base CDATA #IMPLIED
  visible (true|false) 'true'>
<!ELEMENT week (weekendStart,weekendEnd)>
<!ELEMENT weekendStart (#PCDATA)>
<!ELEMENT weekendEnd (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name lang CDATA #REQUIRED>
<!ELEMENT day (name*,dayRule*,holidayRule*)>
<!ATTLIST day id CDATA #REQUIRED>
<!ELEMENT dayRule EMPTY>
<!ATTLIST dayRule
  repeat CDATA 'P1Y'
  fromYear CDATA #IMPLIED
  toYear CDATA #IMPLIED
  year CDATA #IMPLIED
  basedOn CDATA #IMPLIED
  relativeDays CDATA #IMPLIED
  monthOfYear CDATA #IMPLIED
  dayOfMonth CDATA #IMPLIED
  weekOfMonth CDATA #IMPLIED
  dayOfWeek CDATA #IMPLIED
  weekendAdjust (NextWeekday|PreviousWeekday|NearestWeekday) #IMPLIED
  duration CDATA 'P1D'>
<!ELEMENT holidayRule EMPTY>
<!ATTLIST holidayRule
  repeat CDATA 'P1Y'
  fromYear CDATA #IMPLIED
  toYear CDATA #IMPLIED
  year CDATA #IMPLIED
  basedOn CDATA #IMPLIED
  relativeDays CDATA #IMPLIED
  monthOfYear CDATA #IMPLIED
  dayOfMonth CDATA #IMPLIED
  weekOfMonth CDATA #IMPLIED
  dayOfWeek CDATA #IMPLIED
  weekendAdjust (NextWeekday|PreviousWeekday|NearestWeekday) #IMPLIED
  duration CDATA 'P1D'>

=== sourcesense/modeshape-stone/third-parties/joda-time/JodaTimeContrib/holiday/src/java/org/joda/time/contrib/holiday/src/GB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2005 Stephen Colebourne
  -
  -  Licensed under the Apache License, Version 2.0 (the "License");
  -  you may not use this file except in compliance with the License.
  -  You may obtain a copy of the License at
  -
  -      http://www.apache.org/licenses/LICENSE-2.0
  -
  -  Unless required by applicable law or agreed to in writing, software
  -  distributed under the License is distributed on an "AS IS" BASIS,
  -  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  -  See the License for the specific language governing permissions and
  -  limitations under the License.
  -->
<!--
  - Holiday information for GB locale.
  - GB is divided into 4 nations:
  - - GB-ENG - England
  - - GB-WLS - Wales
  - - GB-SCT - Scotland
  - - GB-NIR - Northern Ireland
  -
  - This data is by no means authoritative, and has been collated from various
  - sources. If you think you know better feel free to edit the file.
  - Please send any changes or information to
  - joda-time@lists.sourceforge.net to benefit other users.
  -->
<!DOCTYPE joda-holiday-information SYSTEM "joda-holiday.dtd">
<joda-holiday-information>
  <!-- GB -->
  <!-- Source: http://www.dti.gov.uk/er/bankhol.htm -->
  <!-- Source: http://www.dti.gov.uk/er/bankhis.htm -->
  <holiday-information id="GB">
    <week>
      <weekendStart>6</weekendStart>
      <weekendEnd>7</weekendEnd>
    </week>
    <day id="NewYear">
      <name lang="en">New Year's Day</name>
      <dayRule monthOfYear="1" dayOfMonth="1" />
      <holidayRule fromYear="1974" monthOfYear="1" dayOfMonth="1" weekendAdjust="NextWeekday" />
    </day>
    <day id="ValentinesDay">
      <name lang="en">Valentines Day</name>
      <dayRule monthOfYear="2" dayOfMonth="14" />
    </day>
    <day id="ShroveTuesday">
      <name lang="en">Shrove Tuesday</name>
      <dayRule basedOn="GregorianEaster" relativeDays="-47" />
    </day>
    <day id="AshWednesday">
      <name lang="en">Ash Wednesday</name>
      <dayRule basedOn="GregorianEaster" relativeDays="-46" />
    </day>
    <day id="MothersDay">
      <name lang="en">Mother's Day</name>
      <dayRule basedOn="GregorianEaster" relativeDays="-21" />
    </day>
    <day id="MaundyThursday">
      <name lang="en">Maundy Thursday</name>
      <dayRule basedOn="GregorianEaster" relativeDays="-3" />
    </day>
    <day id="GoodFriday">
      <name lang="en">Good Friday</name>
      <dayRule basedOn="GregorianEaster" relativeDays="-2" />
      <holidayRule fromYear="1871" />
    </day>
    <day id="Easter">
      <name lang="en">Easter</name>
      <dayRule basedOn="GregorianEaster" />
    </day>
    <day id="EasterMonday">
      <name lang="en">Easter Monday</name>
      <dayRule basedOn="GregorianEaster" relativeDays="1" />
    </day>
    <day id="WhitMonday">
      <name lang="en">Whit Monday</name>
      <dayRule basedOn="GregorianEaster" relativeDays="50" />
    </day>
    <day id="AprilFoolsDay">
      <name lang="en">April Fool's Day</name>
      <dayRule monthOfYear="4" dayOfMonth="1" />
    </day>
    <day id="MayDay">
      <name lang="en">May Day</name>
      <dayRule monthOfYear="5" dayOfMonth="1" />
    </day>
    <day id="EarlyMayBankHoliday">
      <name lang="en">Early May Bank Holiday</name>
      <holidayRule fromYear="1978" monthOfYear="5" weekOfMonth="1" dayOfWeek="1" />
      <holidayRule year="1995" monthOfYear="5" dayOfMonth="8" />
    </day>
    <day id="SpringBankHoliday">
      <name lang="en">Spring Bank Holiday</name>
      <holidayRule fromYear="1978" monthOfYear="5" weekOfMonth="-1" dayOfWeek="1" />
      <holidayRule year="2002" monthOfYear="6" dayOfMonth="4" />
    </day>
    <day id="SummerBankHoliday">
      <name lang="en">Summer Bank Holiday</name>
    </day>
    <day id="Halloween">
      <name lang="en">Halloween</name>
      <dayRule monthOfYear="10" dayOfMonth="31" />
    </day>
    <day id="GuyFawkesNight">
      <name lang="en">Guy Fawkes Night</name>
      <dayRule monthOfYear="11" dayOfMonth="5" />
    </day>
    <day id="RemembranceSunday">
      <name lang="en">Remembrance Sunday</name>
      <dayRule monthOfYear="11" weekOfMonth="2" dayOfWeek="7" />
    </day>
    <day id="RemembranceDay">
      <name lang="en">Remembrance Day</name>
      <dayRule monthOfYear="11" dayOfMonth="11" />
    </day>
    <day id="ChristmasEve">
      <name lang="en">Christmas Eve</name>
      <dayRule monthOfYear="12" dayOfMonth="24" />
    </day>
    <day id="ChristmasDay">
      <name lang="en">Christmas Day</name>
      <dayRule monthOfYear="12" dayOfMonth="25" />
      <holidayRule fromYear="1871" weekendAdjust="NextWeekday" />
    </day>
    <day id="BoxingDay">
      <name lang="en">Boxing Day</name>
      <dayRule monthOfYear="12" dayOfMonth="26" />
      <holidayRule fromYear="1974" basedOn="ChristmasDay" relativeDays="1" weekendAdjust="NextWeekday" />
    </day>
    <day id="NewYearsEve">
      <name lang="en">New Year's Eve</name>
      <dayRule monthOfYear="12" dayOfMonth="31" />
    </day>
    <day id="MilleniumDay">
      <name lang="en">Millenium Day</name>
      <dayRule year="1999" monthOfYear="12" dayOfMonth="31" />
    </day>
    <day id="QueenElizabethGoldenJubilee">
      <name lang="en">Queen Elizabeth II Golden Jubilee</name>
      <dayRule year="2002" monthOfYear="6" dayOfMonth="3" />
    </day>
    <day id="RoyalWeddingOfCharlesAndDiana">
      <name lang="en">Royal Wedding of Charles and Diana</name>
      <dayRule year="1981" monthOfYear="7" dayOfMonth="29" />
    </day>
  </holiday-information>
  
  <!-- GB/England -->
  <holiday-information id="GB-ENG" base="GB">
    <day id="EasterMonday">
      <holidayRule fromYear="1871" />
    </day>
    <day id="WhitMonday">
      <holidayRule fromYear="1871" toYear="1966" />
    </day>
    <day id="StGeorgesDay">
      <name lang="en">St George's Day</name>
      <dayRule monthOfYear="4" dayOfMonth="23" />
    </day>
    <day id="SpringBankHoliday">
      <holidayRule fromYear="1967" monthOfYear="5" weekOfMonth="-1" dayOfWeek="1" />
      <holidayRule year="2002" monthOfYear="6" dayOfMonth="4" />
    </day>
    <day id="SummerBankHoliday">
      <holidayRule fromYear="1871" toYear="1964" monthOfYear="8" weekOfMonth="1" dayOfWeek="1" />
      <holidayRule fromYear="1965" monthOfYear="8" weekOfMonth="-1" dayOfWeek="1" />
    </day>
    <day id="BoxingDay">
      <holidayRule fromYear="1871" basedOn="ChristmasDay" relativeDays="1" weekendAdjust="NextWeekday" />
    </day>
  </holiday-information>

  <!-- GB/Wales -->
  <holiday-information id="GB-WLS" base="GB-ENG">
    <day id="StDavidsDay">
      <name lang="en">St David's Day</name>
      <dayRule monthOfYear="3" dayOfMonth="1" />
    </day>
  </holiday-information>

  <!-- GB/Scotland -->
  <holiday-information id="GB-SCT" base="GB">
    <day id="NewYear">
      <holidayRule fromYear="1871" weekendAdjust="NextWeekday" />
      <holidayRule fromYear="1973" weekendAdjust="NextWeekday" duration="P2D" />
    </day>
    <day id="EarlyMayBankHoliday">
      <holidayRule fromYear="1871" monthOfYear="5" weekOfMonth="1" dayOfWeek="1" />
      <holidayRule year="1995" monthOfYear="5" dayOfMonth="8" />
    </day>
    <day id="SummerBankHoliday">
      <holidayRule fromYear="1871" monthOfYear="8" weekOfMonth="1" dayOfWeek="1" />
    </day>
    <day id="StAndrewsDay">
      <name lang="en">St Andrew's Day</name>
      <dayRule monthOfYear="11" dayOfMonth="30" />
    </day>
  </holiday-information>

  <!-- GB/NorthernIreland -->
  <holiday-information id="GB-NIR" base="GB-ENG">
    <day id="StPatricksDay">
      <name lang="en">St Patrick's Day</name>
      <dayRule monthOfYear="3" dayOfMonth="17" />
      <holidayRule fromYear="1903" weekendAdjust="NextWeekday" />
    </day>
    <day id="BattleOfTheBoyne">
      <name lang="en">Battle of the Boyne</name>
      <dayRule monthOfYear="7" dayOfMonth="12" />
      <holidayRule fromYear="1926" weekendAdjust="NextWeekday" />
    </day>
  </holiday-information>

</joda-holiday-information>
